### 3.5.1. 
Constant tensors and variables

In [1]:
import tensorflow as tf

In [2]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [3]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [4]:
tf.random.uniform(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.08009648, 0.0058496 ],
       [0.9541577 , 0.74284744],
       [0.88072574, 0.9386958 ]], dtype=float32)>

In [5]:
tf.random.normal(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.4652126 ,  2.3533165 ],
       [-0.6244105 ,  0.24080466],
       [ 0.49377567,  0.37547287]], dtype=float32)>

In [6]:
import numpy as np

In [7]:
np.empty((3, 2))

array([[1.05629014e-311, 1.05629014e-311],
       [2.55479940e-312, 6.95312594e-310],
       [0.00000000e+000, 7.41098469e-323]])

In [8]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [9]:
np.empty_like(a)

array([0, 0, 0])

In [11]:
x = tf.ones(shape=(2, 1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [13]:
x = tf.zeros(shape = (2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [16]:
x = tf.random.normal(shape = (3, 1), mean = 0., stddev = 1.) # Tensor random values drawn from a normal distribution with mean 0 and standard deviation 1
print(x)

tf.Tensor(
[[-0.05390565]
 [ 2.3938437 ]
 [-0.7930214 ]], shape=(3, 1), dtype=float32)


In [18]:
x = np.random.normal(size=(3, 1), loc = 0., scale = 1.) # Tensor random values drawn from a normal distribution with mean 0 and standard deviation 1
print(x)

[[ 1.73162491]
 [ 1.41040651]
 [-1.51110798]]


In [19]:
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.) # Tensor of random values drawn from uniform distribution between 0 and 1
print(x)

tf.Tensor(
[[0.5365945 ]
 [0.04229391]
 [0.06423676]], shape=(3, 1), dtype=float32)


In [20]:
x = np.random.uniform(size=(3, 1), low=0., high=1.) # Tensor of random values drawn from uniform distribution between 0 and 1
print(x)

[[0.30796546]
 [0.38951335]
 [0.637355  ]]


In [22]:
# Tensorflow tensors are not assignable they are constant
x = np.ones(shape=(2, 2))
print(x)

[[1. 1.]
 [1. 1.]]


In [23]:
x[0, 0] = 0.
print(x)

[[0. 1.]
 [1. 1.]]


In [24]:
x = tf.ones(shape=(2, 2))
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [26]:
# x[0, 0] = 0
# throws an error

In [29]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.5025324 ],
       [ 1.1146352 ],
       [-0.66824096]], dtype=float32)>


In [31]:
v.assign(tf.ones((3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [32]:
v[0, 0].assign(3.)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [33]:
v.assign_add(tf.ones(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>


In [34]:
v.assign_sub(tf.ones(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [36]:
a = tf.ones(shape=(2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
f = tf.matmul(a, b)
f *= d

In [37]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


### 3.5.3 A second look at GradientTape API

In [44]:
input_var = tf.Variable(initial_value = 3.)
input_var # x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [45]:
with tf.GradientTape() as tape:
    result = tf.square(input_var) # x^2

In [46]:
gradient = tape.gradient(result, input_var) # gradient of result w.r.t. input_var
# d(x^2)/d(x) = 2x # 2*3 = 6

In [47]:
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [48]:
# we use this to calculate gradients of the loss w.r.t. it's weights
# gradient = tape.gradient(loss, weights)

In [50]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [57]:
input_const = tf.Variable(2.)
input_const

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [58]:
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(4.0, shape=(), dtype=float32)


In [62]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
print(speed)
print(acceleration)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(9.8, shape=(), dtype=float32)
