In [1]:
import tensorflow as tf

In [2]:
dense = tf.keras.layers.Dense(50, activation="relu",
kernel_initializer="he_normal") # kernel_initializer= "he_uniform" or kernel_initializer= "he_normal"

In [3]:
he_avg_init = tf.keras.initializers.VarianceScaling(scale=2.,
mode="fan_avg",
distribution="uniform")
dense = tf.keras.layers.Dense(50, activation="sigmoid",
kernel_initializer=he_avg_init)

In [4]:
leaky_relu = tf.keras.layers.LeakyReLU(alpha=0.2) # defaults to
alpha=0.3
dense = tf.keras.layers.Dense(50, activation=leaky_relu,
kernel_initializer="he_normal")

In [ ]:
model = tf.keras.models.Sequential([
[...] # more layers
tf.keras.layers.Dense(50, kernel_initializer="he_normal"), #
no activation
tf.keras.layers.LeakyReLU(alpha=0.2), # activation as a
separate layer
[...] # more layers
])

In [19]:
import numpy as np
X = np.random.random((32, 10))
y = np.random.random((10,))

In [20]:
X[0:5, 0:3]

array([[0.28828561, 0.8238137 , 0.74378775],
       [0.84667978, 0.60126885, 0.87518875],
       [0.88428365, 0.72079214, 0.89141943],
       [0.9179469 , 0.99898118, 0.6887181 ],
       [0.86746643, 0.75904523, 0.39331627]])

In [21]:
y[:5]

array([0.23785243, 0.55583396, 0.35968857, 0.21420953, 0.32547072])

In [22]:
y = np.expand_dims(y, axis=0)

In [23]:
y

array([[0.23785243, 0.55583396, 0.35968857, 0.21420953, 0.32547072,
        0.19917452, 0.32715592, 0.23153879, 0.01820738, 0.89376821]])

In [24]:
Y = np.concatenate([y] * 32, axis=0)

In [25]:
Y.shape

(32, 10)

In [26]:
X.shape

(32, 10)

In [29]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
z.shape

(64, 3, 32, 10)

In [34]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
z.shape

(64, 3, 32, 10)

In [35]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)
z.shape

()

In [36]:
x.shape

(32,)

In [37]:
y.shape

(32,)

In [38]:
z

8.356132143007596