In [63]:
import numpy as np

In [64]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [65]:
a = np.random.rand(1, 10,)

In [66]:
np.array(a, dtype='f2')

array([[0.1367, 0.1616, 0.2365, 0.4473, 0.642 , 0.6265, 0.751 , 0.571 ,
        0.8037, 0.635 ]], dtype=float16)

In [67]:
np.full(shape=(1, 5), fill_value=10)

array([[10, 10, 10, 10, 10]])

In [68]:
np.full_like(np.full(shape=(1, 5), fill_value=10), fill_value=100)

array([[100, 100, 100, 100, 100]])

In [69]:
arr = np.zeros((8, 4))

In [70]:
for i in range(8):
    arr[i] = i

In [71]:
arr[[4, 3, 0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [72]:
arr[4, 3,]

4.0

In [73]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [74]:
arr[-3]

array([5., 5., 5., 5.])

In [75]:
arr[-3, -0]

5.0

In [76]:
arr = np.arange(32).reshape((8, 4))

In [77]:
arr[[1, 5, 7, 2],]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [78]:
arr[[0, 3, 1, 2]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [80]:
arr[1, 0]

4

In [81]:
arr[5, 3]

23

In [82]:
arr[7, 1]

29

In [83]:
arr[2, 2]

10

In [84]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [85]:
arr[[1, 5, 7, 2]][:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [86]:
arr[[1, 5, 7, 2]][:, 1]

array([ 5, 21, 29,  9])

In [87]:
arr[[1, 5, 7, 2]][:2, 1]

array([ 5, 21])

In [88]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [89]:
arr[[1, 5, 7, 2]][:2,]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [90]:
arr[[1, 5, 7, 2]][:2, [1, 0]]

array([[ 5,  4],
       [21, 20]])

In [91]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [92]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [93]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([0, 0, 0, 0])

In [94]:
arr[[1, 5, 7, 2]] [:, [0, 3, 1, 2]]

array([[ 0,  7,  5,  6],
       [20,  0, 21, 22],
       [28, 31,  0, 30],
       [ 8, 11,  9,  0]])

In [95]:
arr[[1, 5, 7, 2]] [:, [0, 3, 1, 2]] = 100

In [96]:
arr[[1, 5, 7, 2]] [:, [0, 3, 1, 2]]

array([[ 0,  7,  5,  6],
       [20,  0, 21, 22],
       [28, 31,  0, 30],
       [ 8, 11,  9,  0]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [99]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 100

In [100]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([100, 100, 100, 100])

In [101]:
arr[[1, 5, 7, 2]] #, [0, 3, 1, 2]]

array([[100,   5,   6,   7],
       [ 20,  21,  22, 100],
       [ 28, 100,  30,  31],
       [  8,   9, 100,  11]])

In [105]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[100,   7,   5,   6],
       [ 20, 100,  21,  22],
       [ 28,  31, 100,  30],
       [  8,  11,   9, 100]])

In [103]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] = 6

In [104]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[100,   7,   5,   6],
       [ 20, 100,  21,  22],
       [ 28,  31, 100,  30],
       [  8,  11,   9, 100]])

In [106]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]  = 6

In [107]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([6, 6, 6, 6])